name: Release

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following 2 configurations:
      # 1. <Windows, Release, latest MSVC compiler toolchain on the default runner image, default generator>
      # 2. <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: cl

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Apply patch to PortAudio
        run: git apply ../portaudio.patch
        working-directory: imports/portaudio

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Compress Build Artifacts (Linux)
        if: runner.os == 'Linux'
        run: |
          tar -czvf rtsp-radio-${{ matrix.os }}.tar.gz -C ${{ steps.strings.outputs.build-output-dir }} .

      - name: Upload Build Artifacts (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}-${{ matrix.build_type }}
          path: rtsp-radio-${{ matrix.os }}.tar.gz

      - name: Compress Build Artifacts (Windows)
        if: runner.os == 'Windows'
        run: |
          powershell Compress-Archive -Path ${{ steps.strings.outputs.build-output-dir }}\* -DestinationPath rtsp-radio-${{ matrix.os }}.zip

      - name: Upload Build Artifacts (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.os }}-${{ matrix.build_type }}
          path: rtsp-radio-${{ matrix.os }}.zip

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "npm"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Step 4: Load environment variables from .env
      - name: Load Environment Variables
        run: |
          if [ -f .env ]; then
            export $(cat .env | xargs)
          fi
      # Step 5: Download build artifacts for Windows
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      # Step 7: Run semantic-release
      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --assets "./artifacts/**/*"
